import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('walmart_sales.db')
cursor = conn.cursor()

# Total revenue generated by the retailer
total_revenue_query = '''
    SELECT SUM(Weekly_Sales) AS total_revenue
    FROM sales_data
'''
cursor.execute(total_revenue_query)
total_revenue = cursor.fetchone()[0]
print(f'Total Revenue: ${total_revenue:.2f}')

# The product with the highest total revenue (assuming a Product_ID column)
highest_revenue_product_query = '''
    SELECT Product_ID, SUM(Weekly_Sales) AS total_revenue
    FROM sales_data
    GROUP BY Product_ID
    ORDER BY total_revenue DESC
    LIMIT 1
'''
cursor.execute(highest_revenue_product_query)
highest_revenue_product = cursor.fetchone()
print(f'Product with Highest Revenue: Product ID {highest_revenue_product[0]}, Revenue: ${highest_revenue_product[1]:.2f}')

# The customer who generated the most revenue (assuming a Customer_ID column in a customer_sales_data table)
# Assuming there's a table customer_sales_data with appropriate data
top_revenue_customer_query = '''
    SELECT Customer_ID, SUM(Weekly_Sales) AS total_revenue
    FROM customer_sales_data
    GROUP BY Customer_ID
    ORDER BY total_revenue DESC
    LIMIT 1
'''
cursor.execute(top_revenue_customer_query)
top_revenue_customer = cursor.fetchone()
print(f'Customer with Highest Revenue: Customer ID {top_revenue_customer[0]}, Revenue: ${top_revenue_customer[1]:.2f}')

# Number of unique products sold (assuming a Product_ID column)
unique_products_query = '''
    SELECT COUNT(DISTINCT Product_ID) AS unique_products_sold
    FROM sales_data
'''
cursor.execute(unique_products_query)
unique_products = cursor.fetchone()[0]
print(f'Unique Products Sold: {unique_products}')

# Summary of products sold (assuming a Product_ID column)
product_summary_query = '''
    SELECT Product_ID, COUNT(*) AS times_sold, SUM(Weekly_Sales) AS total_revenue
    FROM sales_data
    GROUP BY Product_ID
'''
cursor.execute(product_summary_query)
product_summary = cursor.fetchall()
print('Product Summary:')
for row in product_summary:
    print(f'Product ID: {row[0]}, Times Sold: {row[1]}, Total Revenue: ${row[2]:.2f}')

# Close connection
conn.close()
